spring.application.name=invoice-system
server.port=8080

# Postgres Properties
db.url=jdbc:postgresql://${HOST}/${DB}
db.username=${USER}
db.password=${PASSWORD}
db.driver-class-name=org.postgresql.Driver

# Optional Hibernate/JPA config
db.ddl-auto=update
spring.jpa.show-sql=true
db.dialect=org.hibernate.dialect.PostgreSQLDialect

# Expose specific actuator endpoints
management.endpoints.web.exposure.include=info,health

# Show detailed health info
management.endpoint.health.show-details=always

# Info endpoint details
info.app.name=Invoice System
info.app.description=Manages invoices, payments, and overdue logic.
info.app.version=1.0.0